add how to create a local bpd chapter
BlackPythonDevs/blackpythondevs pull request #113
Opened 2024-07-29 13:28 UTC by mihrab34

2024-07-31 13:35 UTC, mihrab34 commented
@kjaymiller @activus-d

2024-07-31 16:27 UTC, activus-d requested changes

2024-07-31 16:27 UTC, activus-d commented on how_to/create_a_local_bpd_chapter.md
> +To create one in your local community, send in your email request to meetups@blackpythondevs.com
Well done Rahmat! Can we slightly improve this:

To create a BPD chapter in your local community, send an email request to `meetups@blackpythondevs.com`.

2024-08-01 07:12 UTC, activus-d approved these changes

2024-08-01 07:13 UTC, merged